#!/bin/bash
# S6 run script for Tomcat
# with-contenv injects Kubernetes/Docker env vars (PROFILE, SERVICE_URLs, etc.)
# into the Tomcat JVM process so System.getenv() works correctly

exec /usr/bin/with-contenv /opt/tomcat/bin/catalina.sh run
