# values-dev.yaml — development overrides
global:
  imageRegistry: "sumanth17121988"
  imagePullPolicy: Always

profiles:
  core:
    replicas: 1
  reporting:
    replicas: 1
  mobile:
    replicas: 1

ingress:
  enabled: false
