mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true

service:
  enabled: true
  type: ClusterIP

serviceAccount:
  create: true
  name: otel-collector

clusterRole:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods", "nodes", "nodes/stats", "nodes/proxy", "namespaces"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["apps"]
      resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["batch"]
      resources: ["jobs", "cronjobs"]
      verbs: ["get", "list", "watch"]

extraEnvs:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: NEW_RELIC_LICENSE_KEY
    value: "eu01xxb2c7b50ff6ebdf34097bfd0d1cFFFFNRAL"
  - name: K8S_CLUSTER_NAME
    value: "k8s-cluster"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    kubeletstats:
      collection_interval: 60s
      auth_type: serviceAccount
      endpoint: "https://${env:K8S_NODE_NAME}:10250"
      insecure_skip_verify: true
    hostmetrics:
      collection_interval: 60s
      scrapers:
        cpu: {}
        memory: {}
        disk: {}
        network: {}

  processors:
    batch: {}
    memory_limiter:
      check_interval: 1s
      limit_mib: 400
    k8sattributes:
      auth_type: serviceAccount
    resource:
      attributes:
        - key: k8s.cluster.name
          value: ${env:K8S_CLUSTER_NAME}
          action: upsert
    # Keep logs ONLY from platform namespace — drop everything else
    filter/platform-logs-only:
      logs:
        include:
          match_type: strict
          resource_attributes:
            - key: k8s.namespace.name
              value: platform


  exporters:
    debug:
      verbosity: normal
    otlphttp/newrelic:
      endpoint: "https://otlp.eu01.nr-data.net"
      headers:
        api-key: ${env:NEW_RELIC_LICENSE_KEY}

  service:
    pipelines:
      metrics:
        receivers: [kubeletstats, hostmetrics, otlp]
        processors: [memory_limiter, k8sattributes, resource, batch]
        exporters: [otlphttp/newrelic]
      logs:
        processors: [memory_limiter, k8sattributes, filter/platform-logs-only, resource, batch]
        exporters: [otlphttp/newrelic]
      traces:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, resource, batch]
        exporters: [otlphttp/newrelic, debug]
